### ISSUE TITLE
Make Scroll to Top Arrow "Reacty"

### ISSUE THREAD

**Issue by Nottommy11** [Nottommy11/Online_Game_Store#5]
Make this code look prettier and more elegant using React. This is in the ToTop.js File.
![ToTop](https://user-images.githubusercontent.com/91304333/204223248-fee3f2d5-b9b8-46b4-be38-887aceeb7826.png)

Also, make this code look prettier and more elegant using React. This is in the index.js File.
![index](https://user-images.githubusercontent.com/91304333/204222983-0ad43559-3b36-405f-a8ac-6528bd3122ad.png)

**Comment by AlexOcegueda** [comment]
just made a request! thanks for suggesting the issue.
